---
- name: Execute SQL Statements on Oracle Database
  hosts: all
  # become: true  # Run tasks with elevated privileges (sudo)

  vars:
    oracle_sid: cdb1
    oracle_user: oracle
    oracle_password: oracle
    sql_statements:
      - "SELECT UPPER(VALUE) FROM V$SYSTEM_PARAMETER WHERE UPPER(NAME) = 'AUDIT_SYS_OPERATIONS';"

  environment:
    ORACLE_HOME: "/u01/app/oracle/product/19.0.0/dbhome_1"
    PATH: "%ORACLE_HOME%\bin;%PATH%"
    LD_LIBRARY_PATH: "%ORACLE_HOME%/lib:/lib:/usr/lib"

  tasks:
    - name: Execute SQL Statements
      shell: |
        echo "{{ item }}" | source /etc/profile && sqlplus -S "{{ oracle_user }}/{{ oracle_password }}@{{ oracle_sid }}"
      with_items: "{{ sql_statements }}"
      # args:
      #   executable: /bin/bash