---
- name: Execute SQL Statements on Oracle Database
  hosts: all
  # become: true  # Run tasks with elevated privileges (sudo)

  vars:
    oracle_sid: cdb1
    oracle_user: oracle
    oracle_password: oracle
    sql_statements:
      - "SELECT UPPER(VALUE) FROM V$SYSTEM_PARAMETER WHERE UPPER(NAME) = 'AUDIT_SYS_OPERATIONS';"

  tasks:
    - name: Execute SQL Statements
      shell: |
        echo "{{ item }}" | sqlplus -S "{{ oracle_user }}/{{ oracle_password }}@{{ oracle_sid }}"
      with_items: "{{ sql_statements }}"
      args:
        executable: /bin/bash