---
- name: Execute SQL Statements on Oracle Database
  hosts: all
  # become: true  # Run tasks with elevated privileges (sudo)

  vars:
    oracle_sid: cdb1
    oracle_user: oracle
    oracle_password: oracle
    sql_statements:
      - "SELECT UPPER(VALUE) FROM V$SYSTEM_PARAMETER WHERE UPPER(NAME) = 'AUDIT_SYS_OPERATIONS';"


  tasks:
    - name: Execute SQL Statements
      shell: |
        export ORACLE_BASE=/u01/app/oracle
        export ORACLE_HOME=$ORACLE_BASE/product/19.0.0/dbhome_1
        export PATH=$PATH:/u01/app/oracle/product/19.0.0/dbhome_1
        export LD_LIBRARY_PATH=$ORACLE_HOME/lib:/lib:/usr/lib
        echo "{{ item }}" | /u01/app/oracle/product/19.0.0/dbhome_1/bin/sqlplus -S / as sysdba
      with_items: "{{ sql_statements }}"
      register: result
      # args:
      #   executable: /bin/bash



    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: result
        verbosity: 3